app = "roga-api"
primary_region = "den"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_TIMEZONE = "America/Denver"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
